### ISSUE TITLE
Entrypoint override doesn't work

### ISSUE THREAD

**Issue by abitrolly** [semaphoreci/agent#251]
Overriding `entrypoint` doesn't work.

Documentation https://docs.semaphoreci.com/reference/pipeline-yaml-reference/#containers doesn't have an explicit example, and I try the following syntax, which should execute `ls -la` in `/bin/bash`. `/bin/bash` doesn't happen, and instead default command is executed.

```yaml
version: v1.0
name: Build snap in Docker
agent:
  machine:
    type: f1-standard-2
  containers:
    - name: main
      image: 'yakshaveinc/snapcraft:core24' # Your primary container where commands are run
      entrypoint: /bin/bash

blocks:
  - name: snap build and push
    task:
      jobs:
        - name: Build snap
          commands:
            - ls -la
            - cd snapcrafting/yakshaveinc
```
